#!/bin/bash
#####################################################################################
# 
# forwards local port to port 5005 inside specified k8s pod
#
# USAGE: app-prep-debug <pod-name> [<local-port>]
#
#####################################################################################
if [[ "S1" ]]; then
	if [[ "$2" ]]; then
		localport=$2
	else
		localport=5005
	fi
 	kubectl port-forward $1 $localport:5005	
else
	echo "fail: must specify a pod name!" 
fi
