#!/bin/bash
function show_help() {
  echo Bring github or docker passwords into clipboard
  echo "Usage: ws clip (git (ssh  | user) | docker (token | user)) | help"
  echo "ws"
  echo " . clip"
  echo "   - git"
  echo "     - ssh              ssh password for github access token to clipboard"
  echo "     - user             github user password to clipboard"
  echo "   - docker"
  echo "     - token            dockerhub access token to clipboard"
  echo "     - user             dockerhub user password to clipboard"
  echo "-----------------------------------------------------------------------------------------"
  echo "Note:  '.' optional parameter, '-' mandatory alternative parameters, <> user-defined text"
}
if ! [ -z $1 ]; then
  if [[ $1 == git ]]; then
    if ! [ -z $2 ]; then
      if [[ $2 == ssh ]]; then
        echo -n $GITHUB_SSH_PASSW | xclip -selection clipboard
      elif [[ $2 == cli ]]; then
        echo -n $GITHUB_CLI_TOKEN | xclip -selection clipboard
      elif [[ $2 == user ]]; then
        echo -n $GITHUB_USER_PASSW | xclip -selection clipboard
      else
        show_help
      fi
    fi
  elif [[ $1 == docker ]]; then
    if ! [ -z $2 ]; then
      if [[ $2 == token ]]; then
        echo -n | $DOCKERHUB_TOKEN | xclip -selection clipboard
      elif [[ $2 == user ]]; then
        echo -n $DOCKERHUB_USER | xclip -selection clipboard
      fi
    fi
  else
    show_help
  fi
fi
