#!/bin/bash
if [ -e $1 ]; then
  echo "$1 already exists"
else
  mkdir $1
  echo "/////////////////////////////////////////////////
// export any public explicit submodules...
// pub mod your_sub_module;
  
/////////////////////////////////////////////////
// declare any private explicit submodules...
// mod your_sub_module>;
  
/////////////////////////////////////////////////
// define any private implicit modules...
// mod ypur_private_implicit { .. }
 
/////////////////////////////////////////////////
// implement this modules public interface...

/////////////////////////////////////////////////
// implement this modules private elements...

  " > $1.rs
  echo $1
fi
