#!/bin/bash
session=$1
if [ -z $session ]; then
  session=default
fi
echo $session
homedir=$2
if [ -z $homedir ]; then
  homedir="./"
fi
echo $homedir
function k8s_set_namespace() {
  pane=$1
  namespace=$2
  tmux send-keys -t $pane "kubectl config set-context --current --namespace=$namespace"
}

function k8s_watch_services() {
  pane=$1
  tmux send-keys -t $pane "kubectl get svc -w"
}

function k8s_watch_pods() {
  pane=$1
  tmux send-keys -t $pane "kubectl get pods -w"
}

function set_folder() {
  pane=$1
  tmux send-keys -t $pane "cd $homedir; clear" C-m
}

#github_passw=$(pass repos/github/ssh/vivo_20240212_ed25519)
github_passw=github
#docker_passw=$(pass registries/dockerhub/tokens/build)
docker_passw=dockerhub
#session_exists=$(tmux list-sessions | grep $session)

# Check if the session exists, discarding output
# We can check $? for the exit status (zero for success, non-zero for failure)
tmux has-session -t $session 2>/dev/null
if [ $? != 0 ]; then
  tmux new-session -d -s $session -e DOCKERPW=$docker_passw -e GITPW=$github_passw -c $homedir
  tmux rename-window -t $session:0 "dev"
  tmux new-window -t $session:1 -n "build"
  set_folder $session:1
  tmux new-window -t $session:2 -n "k8s"
  set_folder $session:2
  tmux split-window -t $session:2
  tmux split-window -t $session:2.0 -h
  set_folder $session:2.0
  tmux send-keys -t $session:2.0 'k get svc -w'
  set_folder $session:2.1
  tmux send-keys -t $session:2.1 "k get pods -w"
  set_folder $session:2.2
  tmux send-keys -t $session:2.2 "mnk-start"
  tmux select-pane -t $session:2.2
fi
tmux attach-session -t $session:0
