#!/bin/bash

function k8s_watch_services() {
  pane=$1
  tmux send-keys -t $pane "kubectl get svc -w" C-m
}

function k8s_watch_pods() {
  pane=$1
  tmux send-keys -t $pane "kubectl get pods -w" C-m
}

function show_help() {
  echo "start up a tmux workspace with several windows and initialized github and dockerhub environment."
  echo "K8s minikube cluster startup optional."
  echo
  echo "ws"
  echo " . up                   start a tmux workspace"
  echo "   . -k                 ... with a k8s cluster active"
  echo "     - <namespace>          ... set kubectl namespace, otherwise 'default'"
  echo "   . help               this help"
  echo "-----------------------------------------------------------------------------------------"
  echo "Note:  '.' optional parameter, '-' mandatory alternative parameters, <> user-defined text"
}

echo -n "$GITHUB_CLI_TOKEN" | gh auth login -p ssh --with-token

# retrieve tmux session name
read -p "Session name: " -r session

#kubernetes requested ?
if ! [ -z $1 ]; then
  if [[ "$1" =~ -k ]]; then
    k8s_requested=true
    # start a cluster, if not already up
    if ! [[ $(timeout 5 kubectl cluster-info) =~ (is running at) ]]; then
      echo "No k8s cluster running..."

      ~/bin/mnk up
      if [ $? -lt 0 ]; then
        echo "error while starting up minikube"
        exit -1
      fi
    fi
    # set default namespace if requested
    if ! [ -z $2 ]; then
      kubectl config set-context --current --namespace=$2
    fi
  elif [[ "$1" == help ]]; then
    show_help
    exit
  fi
fi

# Check if the session exists, discarding output
# We can check $? for the exit status (zero for success, non-zero for failure)
tmux has-session -t $session 2>/dev/null
if [ $? != 0 ]; then
  tmux new-session -d -s $session -e DOCKER_USER=$DOCKER_USER -e DOCKER_PASSW=$DOCKER_PASSW -e GITHUB_CLI_TOKEN=$GITHUB_CLI_TOKEN -e GITHUB_SSH_PASSW=$GITHUB_SSH_PASSW -e GITHUB_USER=$GITHUB_USER
  tmux rename-window -t $session:0 "dev"
  tmux new-window -t $session:1 -n "build"

  tmux new-window -t $session:2 -n "test"

  if [ "$k8s_requested" = true ]; then
    tmux new-window -t $session:3 -n "k8s"
    tmux split-window -t $session:3
    tmux split-window -t $session:3.0 -h
    k8s_watch_pods $session:3.0
    k8s_watch_services $session:3.1
    tmux select-pane -t $session:3.2

    tmux new-window -t $session:4 -n "kafka"
    tmux split-window -t $session:4
    tmux split-window -t $session:4.0 -h
    tmux select-pane -t $session:4.2
  fi

fi
tmux attach-session -t $session:0
