#!/bin/bash

source ~/bin-src/wshelp

function k8s_watch_services() {
  pane=$1
  tmux send-keys -t $pane "kubectl get svc -w" Enter
}

function k8s_watch_pods() {
  pane=$1
  tmux send-keys -t $pane "kubectl get pods -w" Enter
}

function list_containers() {
  pane=$1
  tmux send-keys -t $pane "docker container ls -a" Enter
}

function k8s_cluster_is_running() {
  if [ -z "$(kubectl version 2>/dev/null | grep "Server Version")" ]; then
    echo false
  else
    echo true
  fi
}

echo -n "$GITHUB_CLI_TOKEN" | gh auth login -p ssh --with-token

#kubernetes requested ?
if ! [ -z $1 ]; then
  if [[ "$1" == -k ]]; then
    k8s_requested=true
    # start a cluster, if not already up
    if ! $(k8s_cluster_is_running); then
      ~/bin/mnk up
      echo "starting minikube..."
      if [ $? -lt 0 ]; then
        echo "error while starting up minikube"
        exit -1
      fi
    fi
    # set default namespace if requested
    if ! [ -z $2 ]; then
      kubectl config set-context --current --namespace=$2
    fi
  elif [[ "$1" == -o ]]; then
    k8s_requested=true
    if ! $(k8s_cluster_is_running); then
      echo "starting openshift local..."
      crc start
      if [ $? -lt 0 ]; then
        echo "error while starting up openshift"
        exit -1
      fi
      eval $(crc oc-env)
    fi
    # set default namespace if requested
    if ! [ -z $2 ]; then
      kubectl config set-context --current --namespace=$2
    fi

  elif [[ "$1" == help ]]; then
    show_help
    exit
  fi
fi

# retrieve tmux session name
read -p "Session name: " -r session

# Check if the session exists, discarding output
# We can check $? for the exit status (zero for success, non-zero for failure)
tmux has-session -t $session 2>/dev/null
if [ $? != 0 ]; then
  tmux new-session -d -s $session -e DOCKERHUB_TOKEN=$DOCKERHUB_TOKEN -e DOCKER_HUB_USER=$DOCKERHUB__USER -e DOCKER_PASSW=$DOCKERHUB_USER_PASSW -e GITHUB_CLI_TOKEN=$GITHUB_CLI_TOKEN -e GITHUB_SSH_PASSW=$GITHUB_SSH_PASSW -e GITHUB_USER=$GITHUB_USER -e GITHUB_USER_PASSW=$GITHUB_USER_PASSW
  tmux rename-window -t $session:0 "dev"

  tmux new-window -t $session:1 -n "build"
  tmux split-window -t $session:1
  tmux send-keys -t $session:1.0 "gst" Enter
  tmux send-keys -t $session:1.1 "glola" Enter

  tmux new-window -t $session:2 -n "run"
  tmux split-window -t $session:2
  list_containers $session:2.0
  tmux select-pane -t $session:2.1

  tmux new-window -t $session:3 -n "test"

  tmux new-window -t $session:4 -n "NATS"
  tmux split-window -t $session:4
  tmux split-window -t $session:4.0 -h
  tmux select-pane -t $session:4.1

  tmux new-window -t $session:5 -n "postgres"
  tmux split-window -t $session:5
  tmux split-window -t $session:5.0 -h
  tmux select-pane -t $session:5.1

  if [ "$k8s_requested" = true ]; then
    tmux new-window -t $session:6 -n "k8s"
    tmux split-window -t $session:6
    tmux split-window -t $session:6.0 -h
    k8s_watch_pods $session:6.0
    k8s_watch_services $session:6.1
    tmux select-pane -t $session:6.2
  fi
fi

tmux attach-session -t $session:0
